---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ mailtrain_service_name }}'
    consul_services:
      - name: '{{ mailtrain_service_name }}'
        tags: ['mailtrain', 'newsletter']
        # we advertise the port with basic auth
        port: '{{ mailtrain_app_cont_port }}'
        checks:
          - id: '{{ mailtrain_service_name }}-health'
            name: MailTrain Service Healthcheck
            type: http
            http: 'http://localhost:{{ mailtrain_app_cont_port }}/css/mailtrain.css'
